title: Musings
email: randal@brandmine.ca
description: >- 
  Exploring the intersection of brand strategy, consumer psychology, and market trends. Musings offers fresh perspectives on what makes brands resonate, with occasional detours into whatever fascinating topics catch our attention along the way.
baseurl: "" # With a custom domain, this should be empty
url: "https://blog.brandomy.com" # Your custom domain with https protocol
theme: minima
timezone: Asia/Singapore