title: Brandomy
email: randal@brandmine.io
description: >- 
  Exploring the intersection of brand strategy, consumer psychology, and market trends. Brandomy offers fresh perspectives on what makes brands resonate, with occasional detours into whatever fascinating topics catch our attention along the way.
baseurl: "" # With a custom domain, this should be empty
url: "https://blog.brandomy.com" # Your custom domain with https protocol
theme: minima
timezone: Asia/Singapore

# Specify which pages to include in the header navigation
header_pages:
  - about.md
  # Add any other pages you want in navigation
  # - contact.md
  # - projects.md

sass:
  quiet_deps: true
  style: compressed


# Add these lines to your _config.yml
permalink: /:year/:month/:day/:title/

# Category settings
collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"